sudo: required
language: ruby

services:
    - docker

before_install:
    - docker pull gerdes/rock

script:
    - docker run -it gerdes/rock bash -c ". env.sh && aup && amake perception/orogen/hazard_detector"
